from pptx import Presentation

def generate_ppt_report(

    report_data,
    output_path

):

    ppt = Presentation()

    # Slide 1: Title
    slide = ppt.slides.add_slide(ppt.slide_layouts[0])
    slide.shapes.title.text = report_data.get("title", "Research Report")
    slide.placeholders[1].text = "Research Intelligence Presentation\nGenerated by ResearchMind AI"

    # Slide 2: Executive Summary
    slide = ppt.slides.add_slide(ppt.slide_layouts[1])
    slide.shapes.title.text = "Executive Summary"
    slide.placeholders[1].text = report_data.get("summary", "")

    # Slide 3: Key Contributions
    slide = ppt.slides.add_slide(ppt.slide_layouts[1])
    slide.shapes.title.text = "Key Contributions"
    contribs = report_data.get("key_contributions", [])
    if isinstance(contribs, list):
        contrib_text = "\n".join([f"• {c}" for c in contribs])
    else:
        contrib_text = str(contribs)
    slide.placeholders[1].text = contrib_text or "No key contributions generated."

    # Slide 4: Strengths
    slide = ppt.slides.add_slide(ppt.slide_layouts[1])
    slide.shapes.title.text = "Strengths"
    strengths = report_data.get("strengths", [])
    if isinstance(strengths, list):
        strengths_text = "\n".join([f"• {s}" for s in strengths])
    else:
        strengths_text = str(strengths)
    slide.placeholders[1].text = strengths_text or "No strengths specified."

    # Slide 5: Weaknesses
    slide = ppt.slides.add_slide(ppt.slide_layouts[1])
    slide.shapes.title.text = "Weaknesses"
    weaknesses = report_data.get("weaknesses", [])
    if isinstance(weaknesses, list):
        weaknesses_text = "\n".join([f"• {w}" for w in weaknesses])
    else:
        weaknesses_text = str(weaknesses)
    slide.placeholders[1].text = weaknesses_text or "No weaknesses specified."

    # Slide 6: Research Scores
    slide = ppt.slides.add_slide(ppt.slide_layouts[1])
    slide.shapes.title.text = "Research Scores"
    scores = report_data.get("research_scores", {})
    if isinstance(scores, dict):
        scores_text = "\n".join([f"{k.replace('_', ' ').title()}: {v}/10" for k, v in scores.items()])
    else:
        scores_text = str(scores)
    slide.placeholders[1].text = scores_text or "No scores specified."

    # Slide 7: Future Work
    slide = ppt.slides.add_slide(ppt.slide_layouts[1])
    slide.shapes.title.text = "Future Work & Recommendations"
    fw_text = report_data.get("future_work", "")
    recs = report_data.get("recommendations", [])
    if recs:
        if isinstance(recs, list):
            fw_text += "\n\nRecommendations:\n" + "\n".join([f"• {r}" for r in recs])
        else:
            fw_text += "\n\nRecommendations:\n" + str(recs)
    slide.placeholders[1].text = fw_text or "No future work suggested."

    # Slide 8: Conclusion
    slide = ppt.slides.add_slide(ppt.slide_layouts[1])
    slide.shapes.title.text = "Conclusion"
    slide.placeholders[1].text = "The paper presents valuable contributions in its field, with identified areas for improvement and future extension.\n\nThank you!"

    ppt.save(str(output_path))
    return output_path
